import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { db } from "@/lib/db";
import { formatDate, cn } from "@/lib/utils";
import { type RiskLevel, RISK_COLORS, RISK_LABELS } from "@/lib/analysis-schema";
import { PublicReportViewer } from "@/components/report/PublicReportViewer";

interface Props {
  params: Promise<{ token: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params;
  const analysis = await db.analysis.findUnique({
    where: { shareToken: token },
    select: { description: true, riskLevel: true },
  });

  if (!analysis) {
    return { title: "Report not found" };
  }

  const preview = analysis.description.slice(0, 120);
  return {
    title: "Shared EU AI Act Compliance Report | Regumatrix",
    description: `EU AI Act compliance analysis: ${preview}…`,
    robots: { index: false, follow: false }, // don't index shared reports
  };
}

export default async function SharedReportPage({ params }: Props) {
  const { token } = await params;

  const analysis = await db.analysis.findUnique({
    where: { shareToken: token },
    select: {
      id: true,
      description: true,
      result: true,
      articlesHit: true,
      riskLevel: true,
      roleFound: true,
      createdAt: true,
    },
  });

  if (!analysis) notFound();

  const knownRisk =
    analysis.riskLevel && analysis.riskLevel in RISK_COLORS
      ? (analysis.riskLevel as RiskLevel)
      : null;

  return (
    <div className="py-10">
      <div className="container mx-auto max-w-3xl px-4 space-y-6">
        {/* Banner */}
        <div className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-muted-foreground">
          This is a shared EU AI Act compliance report generated by{" "}
          <Link href="/" className="font-semibold text-primary hover:underline">
            Regumatrix
          </Link>
          . Run your own free analysis →{" "}
          <Link href="/sign-up" className="font-semibold text-primary hover:underline">
            Get started
          </Link>
        </div>

        {/* Header */}
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">EU AI Act Compliance Report</h1>
            <p className="mt-1 text-sm text-muted-foreground">{formatDate(analysis.createdAt)}</p>
          </div>
          {knownRisk && (
            <div
              className={cn(
                "flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm font-medium",
                RISK_COLORS[knownRisk].pillBg,
                RISK_COLORS[knownRisk].pillBorder,
                RISK_COLORS[knownRisk].text,
              )}
            >
              <span className={cn("h-2 w-2 rounded-full", RISK_COLORS[knownRisk].dot)} />
              {RISK_LABELS[knownRisk]}
            </div>
          )}
        </div>

        {/* Description */}
        <div className="rounded-xl border border-border bg-muted/30 p-5">
          <p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
            System Description
          </p>
          <p className="text-sm leading-relaxed">{analysis.description}</p>
        </div>

        {/* Meta */}
        {(analysis.roleFound) && (
          <div className="flex flex-wrap gap-4 text-sm text-muted-foreground">
            <div>
              <span className="font-medium text-foreground">Operator role:</span>{" "}
              <span className="capitalize">{analysis.roleFound}</span>
            </div>
          </div>
        )}

        {/* Analysis content */}
        <PublicReportViewer
          result={analysis.result}
          articlesHit={analysis.articlesHit}
          analysisId={analysis.id}
        />

        {/* Footer CTA */}
        <div className="rounded-xl border border-primary/20 bg-primary/5 p-6 text-center">
          <p className="text-sm font-medium mb-3">
            Need to check your own AI system for EU AI Act compliance?
          </p>
          <Link
            href="/sign-up"
            className="inline-flex h-9 items-center rounded-lg bg-primary px-6 text-sm font-semibold text-primary-foreground hover:bg-primary/90"
          >
            Get a free compliance report →
          </Link>
        </div>
      </div>
    </div>
  );
}
